on: [push]

jobs:
  test-otlp-output:
    runs-on: ubuntu-latest
    name: A job to test OTLP output
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Send data to OTLP backend
        uses: codeboten/github-action-to-otlp@v1
        with:
          endpoint: ${{ vars.OTEL_COLL_HTTP_END_POINT }}
